NODE_FILE: ./3-Model-Files/cds-model-wprog.yml
DATA_FOLDER: ./0-Raw-Data-Files/cds_raw_data_files_v1.3/
DATA_BATCH_NAME: cds_data_2023-3-17
OUTPUT_FOLDER: ./4-Transformed-Data-Files/cds_transformed_data_files_v1.3/
RATIO_LIMIT: 0.75
S3_BUCKET: bruce-cds
S3_RAWDATA_SUBFOLDER: cds_data_2023-3-4/
MODEL_FILE_PROPS: ./3-Model-Files/cds-model-props.yml
CLEAN_DICT: ./2-Config-Files/cds_config_v1.3/cds_clean_dict_v1.3.yaml
RAW_DATA_DICTIONARY: ./2-Config-Files/cds_config_v1.3/cds_raw_dict_v1.3.yaml
VALIDATION_SPREAD_SHEET: ./2-Config-Files/cds_config/UI-database mappings.xlsx
ID_VALIDATION_RESULT_FOLDER: ./5-ID-Validation-Result
PARENT_MAPPING_COLUMNS:
  -
    node: participant
    parent_node: study
    property: phs_accession
  -
    node: sample
    parent_node: participant
    property: participant_id
  -
    node: file
    parent_node: sample
    property: sample_id
  -
    node: genomic_info
    parent_node: file
    property: file_id
  -
    node: diagnosis
    parent_node: participant
    property: participant_id
  -
    node: study
    parent_node: program
    property: program_acronym
  -
    node: file
    parent_node: study
    property: phs_accession

COMBINE_NODE:
  -
    node: study
    id_column: phs_accession
  -
    node: program
    id_column: program_acronym
  -
    node: diagnosis
    id_column: diagnosis_id

COMBINE_COLUMN:
  -
    node: sample
    column1: sample_id
    column2: sample_type
    new_column: sample_id

SECONDARY_ID_COLUMN:
  -
    node: diagnosis
    node_id: diagnosis_id
    secondary_id: participant.participant_id
  -
    node: genomic_info
    node_id: genomic_info_id
    secondary_id: file.file_id

REMOVE_NODES:
  #- diagnosis
  - treatment

VALIDATION_FILE: ./2-Config-Files/cds_config/UI-database mappings.xlsx
NODE_ID_FIELD:
  program: program_acronym
  file: file_id
  sample: sample_id
  participant: participant_id
  study: phs_accession
  diagnosis: diagnosis_id
  genomic_info: genomic_info_id